---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
      eqeqeq:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: 
  - "scripts/garbochess-m.js"
  - "scripts/garbochess-b.js"
  - "scripts/jquery-2.0.3.js"
